--- #YAML:1.0
name:               Search-OpenSearch
version:            0.08
abstract:           provide search results in OpenSearch format
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CHI:                 0
    Data::Pageset:       0
    JSON:                0
    Rose::ObjectX::CAF:  0
    Scalar::Util:        0
    Search::Tools:       0
    Test::More:          0
    URI::Encode:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
