---
abstract: 'provide search results in OpenSearch format'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-OpenSearch
no_index:
  directory:
    - t
    - inc
requires:
  CHI: 0
  Data::Pageset: 0
  Data::UUID: 0
  JSON: 0
  Rose::ObjectX::CAF: 0
  Scalar::Util: 0
  Search::Tools: 0
  Sort::SQL: 0
  Test::More: 0
  URI::Encode: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch
  homepage: https://github.com/karpet/search-opensearch-perl
  license: http://dev.perl.org/licenses/
  repository: git://github.com/karpet/search-opensearch-perl.git
version: 0.16
