--- #YAML:1.0
name:               Search-OpenSearch
version:            0.14
abstract:           provide search results in OpenSearch format
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CHI:                 0
    Data::Pageset:       0
    JSON:                0
    perl:                5.008003
    Rose::ObjectX::CAF:  0
    Scalar::Util:        0
    Search::Tools:       0
    Test::More:          0
    URI::Encode:         0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch
    homepage:    http://perl.peknet.com/
    license:     http://dev.perl.org/licenses/
    repository:  http://svn.peknet.com/perl/Search-OpenSearch/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
